### PR TITLE
Fix list to update animal list

### LINKED ISSUE #101: List should list all (person and animal)
Currently list only lists person

### PR DESCRIPTION
**Pull request by morpheuschoo**
Fix #101

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ListCommand.java [hunk 1]
```diff
@@ -19,6 +20,7 @@ public class ListCommand extends Command {
     public CommandResult execute(Model model) {
         requireNonNull(model);
         model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
+        model.updateFilteredAnimalList(PREDICATE_SHOW_ALL_ANIMALS);
```
Comment (blurfrost) [inline src/main/java/seedu/address/logic/commands/ListCommand.java]: LGTM!

**Review by blurfrost — APPROVED** [review]

File: src/main/java/seedu/address/logic/commands/ListCommand.java [hunk 2]
```diff
@@ -1,6 +1,7 @@
 package seedu.address.logic.commands;
 
 import static java.util.Objects.requireNonNull;
+import static seedu.address.model.Model.PREDICATE_SHOW_ALL_ANIMALS;
```
Comment (McFishhh) [inline src/main/java/seedu/address/logic/commands/ListCommand.java]: Nice lexicographical import order!
